---

# the service will listen on this port
port: 8345

# the base url preceding the service endpoint
base_url: /api/1.0

# the location on the server under which runfolders are stored
# the parameters "host" and "runfolder" can be used inside curly brackets (e.g. {host}) and will be substituted
# for each request
datadir: tests/resources/{host}/runfolders/{runfolder}

# the url where the snpseq-data service can be accessed
snpseq_data_url: http://localhost:9191

# the path to the snpseq_metadata python package main script
snpseq_metadata_executable: .venv/bin/snpseq_metadata
