---

port: 8345
base_url: /api/1.0
datadir: /Users/pontus/Documents/code/snpseq_metadata/tests/resources
snpseq_data_url: http://localhost:9191
snpseq_metadata_executable: /Users/pontus/Documents/code/snpseq_metadata/venv_/bin/snpseq_metadata
